export const FETCH_LOGIN_STATE_START = "FETCH_LOGIN_STATE_START";
export const FETCH_LOGIN_STATE_ACK = "FETCH_LOGIN_STATE_ACK";
export const FETCH_LOGIN_STATE_ERROR = "FETCH_LOGIN_STATE_ERROR";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_ACK = "LOGOUT_ACK";
export const LOGOUT_ERROR = "LOGOUT_ERROR";