export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_ACK = "LOGOUT_ACK";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const FETCH_SCORETABLE_START = "FETCH_SCORETABLE_START";
export const FETCH_SCORETABLE_ACK = "FETCH_SCORETABLE_ACK";
export const FETCH_SCORETABLE_ERROR = "FETCH_SCORETABLE_ERROR";

export const FETCH_AVAILABLE_FIXTURES_START = "FETCH_AVAILABLE_FIXTURES_START";
export const FETCH_AVAILABLE_FIXTURES_ACK = "FETCH_AVAILABLE_FIXTURES_ACK";
export const FETCH_AVAILABLE_FIXTURES_ERROR = "FETCH_AVAILABLE_FIXTURES_ERROR";

export const FETCH_BETS_START = "FETCH_BETS_START";
export const FETCH_BETS_ACK = "FETCH_BETS_ACK";
export const FETCH_BETS_ERROR = "FETCH_BETS_ERROR";

export const FETCH_ALL_FIXTURES_START = "FETCH_ALL_FIXTURES_START";
export const FETCH_ALL_FIXTURES_ACK = "FETCH_ALL_FIXTURES_ACK";
export const FETCH_ALL_FIXTURES_ERROR = "FETCH_ALL_FIXTURES_ERROR";

export const POST_BET_START = "POST_BET_START";
export const POST_BET_ACK = "POST_BET_ACK";
export const POST_BET_ERROR = "POST_BET_ERROR";