export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_ACK = "LOGOUT_ACK";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const FETCH_SCORETABLE_START = "FETCH_SCORETABLE_START";
export const FETCH_SCORETABLE_ACK = "FETCH_SCORETABLE_ACK";
export const FETCH_SCORETABLE_ERROR = "FETCH_SCORETABLE_ERROR";
